// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v2.Models
{

    /// <summary>
    /// Defines values for BasicEnum.
    /// </summary>
    public static class BasicEnum
    {
        /// <summary>
        /// The none
        /// </summary>
        public const string None = "None";
        /// <summary>
        /// The something1
        /// </summary>
        public const string Something1 = "Something1";
        /// <summary>
        /// The something2
        /// </summary>
        public const string Something2 = "Something2";
    }
}
