//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepSleep.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepSleep.Resources.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 431.000001|Request header &apos;{0}&apos; cannot exceed {1} characters in length..
        /// </summary>
        internal static string HeaderLengthExceeded {
            get {
                return ResourceManager.GetString("HeaderLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.000003|Could not deserialize request..
        /// </summary>
        internal static string RequestBodyDeserializationError {
            get {
                return ResourceManager.GetString("RequestBodyDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 414.000001|Request uri cannot exceed {0} characters in length..
        /// </summary>
        internal static string RequestUriLengthExceeded {
            get {
                return ResourceManager.GetString("RequestUriLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.000004|&apos;{0}&apos; Is in an incorrect format and could not be bound..
        /// </summary>
        internal static string UriBindingError {
            get {
                return ResourceManager.GetString("UriBindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.000005|Uri type conversion for &apos;{0}&apos; with value &apos;{1}&apos; could not be converted to type {2}..
        /// </summary>
        internal static string UriBindingValueError {
            get {
                return ResourceManager.GetString("UriBindingValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.000002|Duplicate query variable path &apos;{0}&apos;..
        /// </summary>
        internal static string UriQueryBindingError {
            get {
                return ResourceManager.GetString("UriQueryBindingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.000001|Duplicate route variable path &apos;{0}&apos;..
        /// </summary>
        internal static string UriRouteBindingError {
            get {
                return ResourceManager.GetString("UriRouteBindingError", resourceCulture);
            }
        }
    }
}
