// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v3
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for DeepSleepApi.
    /// </summary>
    public static partial class DeepSleepApiExtensions
    {
            /// <summary>
            /// Posts the basic object model with no doc attributes.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The route identifier.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static BasicObject PostBasicObjectModelNoDocAttributes(this IDeepSleepApi operations, int id, BasicObject body = default(BasicObject), string xCorrelationId = default(string))
            {
                return operations.PostBasicObjectModelNoDocAttributesAsync(id, body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Posts the basic object model with no doc attributes.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The route identifier.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<BasicObject> PostBasicObjectModelNoDocAttributesAsync(this IDeepSleepApi operations, int id, BasicObject body = default(BasicObject), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostBasicObjectModelNoDocAttributesWithHttpMessagesAsync(id, body, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Posts the enum model with URI bound enums.
            /// </summary>
            /// <remarks>
            /// Offically posts the enum object to the service
            ///
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='explicitEnumProperty'>
            /// Gets or sets the explicit enum property. Possible values include: 'None',
            /// 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static EnumUriObjectModelRs PostEnumUriModelNoDocAttributes(this IDeepSleepApi operations, string explicitEnumProperty = default(string), string xCorrelationId = default(string))
            {
                return operations.PostEnumUriModelNoDocAttributesAsync(explicitEnumProperty, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Posts the enum model with URI bound enums.
            /// </summary>
            /// <remarks>
            /// Offically posts the enum object to the service
            ///
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='explicitEnumProperty'>
            /// Gets or sets the explicit enum property. Possible values include: 'None',
            /// 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<EnumUriObjectModelRs> PostEnumUriModelNoDocAttributesAsync(this IDeepSleepApi operations, string explicitEnumProperty = default(string), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostEnumUriModelNoDocAttributesWithHttpMessagesAsync(explicitEnumProperty, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Puts the enum model with URI bound enums.
            /// </summary>
            /// <remarks>
            /// Offically puts the enum object to the service
            ///
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='explicitEnumProperty'>
            /// Gets or sets the explicit enum property. Possible values include: 'None',
            /// 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static EnumUriObjectModelRs PutEnumUriModelNoDocAttributes(this IDeepSleepApi operations, string explicitEnumProperty = default(string), string xCorrelationId = default(string))
            {
                return operations.PutEnumUriModelNoDocAttributesAsync(explicitEnumProperty, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Puts the enum model with URI bound enums.
            /// </summary>
            /// <remarks>
            /// Offically puts the enum object to the service
            ///
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='explicitEnumProperty'>
            /// Gets or sets the explicit enum property. Possible values include: 'None',
            /// 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<EnumUriObjectModelRs> PutEnumUriModelNoDocAttributesAsync(this IDeepSleepApi operations, string explicitEnumProperty = default(string), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PutEnumUriModelNoDocAttributesWithHttpMessagesAsync(explicitEnumProperty, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Patch the enum model with URI bound enums.
            /// </summary>
            /// <remarks>
            /// Offically patches the enum object to the service
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='explicitEnumProperty'>
            /// The explicit enum property. Possible values include: 'None', 'Item1',
            /// 'Item2'
            /// </param>
            /// <param name='nullableExplicitEnumProperty'>
            /// The nullable explicit enum property. Possible values include: 'None',
            /// 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static EnumUriObjectModelRs PatchEnumUriModelNoDocAttributes(this IDeepSleepApi operations, string explicitEnumProperty = default(string), string nullableExplicitEnumProperty = default(string), string xCorrelationId = default(string))
            {
                return operations.PatchEnumUriModelNoDocAttributesAsync(explicitEnumProperty, nullableExplicitEnumProperty, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Patch the enum model with URI bound enums.
            /// </summary>
            /// <remarks>
            /// Offically patches the enum object to the service
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='explicitEnumProperty'>
            /// The explicit enum property. Possible values include: 'None', 'Item1',
            /// 'Item2'
            /// </param>
            /// <param name='nullableExplicitEnumProperty'>
            /// The nullable explicit enum property. Possible values include: 'None',
            /// 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<EnumUriObjectModelRs> PatchEnumUriModelNoDocAttributesAsync(this IDeepSleepApi operations, string explicitEnumProperty = default(string), string nullableExplicitEnumProperty = default(string), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PatchEnumUriModelNoDocAttributesWithHttpMessagesAsync(explicitEnumProperty, nullableExplicitEnumProperty, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets the enum from route.
            /// </summary>
            /// <remarks>
            /// Offically posts the enum nul object to the service
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enumValue'>
            /// The enum value. Possible values include: 'None', 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static string GetEnumInRouteSimpleMember(this IDeepSleepApi operations, string enumValue, string xCorrelationId = default(string))
            {
                return operations.GetEnumInRouteSimpleMemberAsync(enumValue, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the enum from route.
            /// </summary>
            /// <remarks>
            /// Offically posts the enum nul object to the service
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enumValue'>
            /// The enum value. Possible values include: 'None', 'Item1', 'Item2'
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> GetEnumInRouteSimpleMemberAsync(this IDeepSleepApi operations, string enumValue, string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetEnumInRouteSimpleMemberWithHttpMessagesAsync(enumValue, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enumValue'>
            /// The enum value. Possible values include: 'None', 'Item1', 'Item2'
            /// </param>
            public static void HeadEnumInRouteSimpleMember(this IDeepSleepApi operations, string enumValue)
            {
                operations.HeadEnumInRouteSimpleMemberAsync(enumValue).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='enumValue'>
            /// The enum value. Possible values include: 'None', 'Item1', 'Item2'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadEnumInRouteSimpleMemberAsync(this IDeepSleepApi operations, string enumValue, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadEnumInRouteSimpleMemberWithHttpMessagesAsync(enumValue, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Posts the int32 model with URI bound values.
            /// </summary>
            /// <remarks>
            /// Offically posts the int32 uri to the service
            ///
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='int32Property'>
            /// Gets or sets the int32 property.
            /// </param>
            /// <param name='nullableInt32Property'>
            /// Gets or sets the nullable int32 property.
            /// </param>
            /// <param name='uInt32Property'>
            /// Gets or sets the u int32 property.
            /// </param>
            /// <param name='nullableUInt32Property'>
            /// Gets or sets the nullable u int32 property.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static Int32ObjectModelRq PostInt32UriModelNoDocAttributes(this IDeepSleepApi operations, int? int32Property = default(int?), int? nullableInt32Property = default(int?), int? uInt32Property = default(int?), int? nullableUInt32Property = default(int?), string xCorrelationId = default(string))
            {
                return operations.PostInt32UriModelNoDocAttributesAsync(int32Property, nullableInt32Property, uInt32Property, nullableUInt32Property, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Posts the int32 model with URI bound values.
            /// </summary>
            /// <remarks>
            /// Offically posts the int32 uri to the service
            ///
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='int32Property'>
            /// Gets or sets the int32 property.
            /// </param>
            /// <param name='nullableInt32Property'>
            /// Gets or sets the nullable int32 property.
            /// </param>
            /// <param name='uInt32Property'>
            /// Gets or sets the u int32 property.
            /// </param>
            /// <param name='nullableUInt32Property'>
            /// Gets or sets the nullable u int32 property.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Int32ObjectModelRq> PostInt32UriModelNoDocAttributesAsync(this IDeepSleepApi operations, int? int32Property = default(int?), int? nullableInt32Property = default(int?), int? uInt32Property = default(int?), int? nullableUInt32Property = default(int?), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostInt32UriModelNoDocAttributesWithHttpMessagesAsync(int32Property, nullableInt32Property, uInt32Property, nullableUInt32Property, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets the int32 combined route and query values.
            /// </summary>
            /// <remarks>
            /// Offically gets the combined int32 values
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='routeint'>
            /// The route int.
            /// </param>
            /// <param name='queryInt1'>
            /// The query int1.
            /// </param>
            /// <param name='queryInt2'>
            /// The query int2.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static int? GetInt32ValuesOverriddenOpId(this IDeepSleepApi operations, int routeint, int? queryInt1 = default(int?), int? queryInt2 = default(int?), string xCorrelationId = default(string))
            {
                return operations.GetInt32ValuesOverriddenOpIdAsync(routeint, queryInt1, queryInt2, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the int32 combined route and query values.
            /// </summary>
            /// <remarks>
            /// Offically gets the combined int32 values
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='routeint'>
            /// The route int.
            /// </param>
            /// <param name='queryInt1'>
            /// The query int1.
            /// </param>
            /// <param name='queryInt2'>
            /// The query int2.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<int?> GetInt32ValuesOverriddenOpIdAsync(this IDeepSleepApi operations, int routeint, int? queryInt1 = default(int?), int? queryInt2 = default(int?), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetInt32ValuesOverriddenOpIdWithHttpMessagesAsync(routeint, queryInt1, queryInt2, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='routeint'>
            /// The route int.
            /// </param>
            /// <param name='queryInt1'>
            /// The query int1.
            /// </param>
            /// <param name='queryInt2'>
            /// The query int2.
            /// </param>
            public static void HeadInt32ValuesOverriddenOpId(this IDeepSleepApi operations, int routeint, int? queryInt1 = default(int?), int? queryInt2 = default(int?))
            {
                operations.HeadInt32ValuesOverriddenOpIdAsync(routeint, queryInt1, queryInt2).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='routeint'>
            /// The route int.
            /// </param>
            /// <param name='queryInt1'>
            /// The query int1.
            /// </param>
            /// <param name='queryInt2'>
            /// The query int2.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadInt32ValuesOverriddenOpIdAsync(this IDeepSleepApi operations, int routeint, int? queryInt1 = default(int?), int? queryInt2 = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadInt32ValuesOverriddenOpIdWithHttpMessagesAsync(routeint, queryInt1, queryInt2, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Simples the i list int array response.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static IList<int?> GetSimpleIlistIntArrayResponse(this IDeepSleepApi operations, int? count = default(int?), string xCorrelationId = default(string))
            {
                return operations.GetSimpleIlistIntArrayResponseAsync(count, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the i list int array response.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> GetSimpleIlistIntArrayResponseAsync(this IDeepSleepApi operations, int? count = default(int?), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSimpleIlistIntArrayResponseWithHttpMessagesAsync(count, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            public static void HeadSimpleIlistIntArrayResponse(this IDeepSleepApi operations, int? count = default(int?))
            {
                operations.HeadSimpleIlistIntArrayResponseAsync(count).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadSimpleIlistIntArrayResponseAsync(this IDeepSleepApi operations, int? count = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadSimpleIlistIntArrayResponseWithHttpMessagesAsync(count, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Simples the i list int array request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The ints.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static IList<int?> PostSimpleIlistIntArrayRequest(this IDeepSleepApi operations, IList<int?> body = default(IList<int?>), string xCorrelationId = default(string))
            {
                return operations.PostSimpleIlistIntArrayRequestAsync(body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the i list int array request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The ints.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> PostSimpleIlistIntArrayRequestAsync(this IDeepSleepApi operations, IList<int?> body = default(IList<int?>), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostSimpleIlistIntArrayRequestWithHttpMessagesAsync(body, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Simples the i enumerable int array response.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static IList<int?> GetSimpleIenumerableIntArrayResponse(this IDeepSleepApi operations, int? count = default(int?), string xCorrelationId = default(string))
            {
                return operations.GetSimpleIenumerableIntArrayResponseAsync(count, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the i enumerable int array response.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> GetSimpleIenumerableIntArrayResponseAsync(this IDeepSleepApi operations, int? count = default(int?), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSimpleIenumerableIntArrayResponseWithHttpMessagesAsync(count, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            public static void HeadSimpleIenumerableIntArrayResponse(this IDeepSleepApi operations, int? count = default(int?))
            {
                operations.HeadSimpleIenumerableIntArrayResponseAsync(count).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadSimpleIenumerableIntArrayResponseAsync(this IDeepSleepApi operations, int? count = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadSimpleIenumerableIntArrayResponseWithHttpMessagesAsync(count, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Simples the i enumerable int array request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The ints.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static IList<int?> PostSimpleIenumerableIntArrayRequest(this IDeepSleepApi operations, IList<int?> body = default(IList<int?>), string xCorrelationId = default(string))
            {
                return operations.PostSimpleIenumerableIntArrayRequestAsync(body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the i enumerable int array request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The ints.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> PostSimpleIenumerableIntArrayRequestAsync(this IDeepSleepApi operations, IList<int?> body = default(IList<int?>), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostSimpleIenumerableIntArrayRequestWithHttpMessagesAsync(body, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Simples the array int array response.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static IList<int?> GetSimpleArrayIntArrayResponse(this IDeepSleepApi operations, int? count = default(int?), string xCorrelationId = default(string))
            {
                return operations.GetSimpleArrayIntArrayResponseAsync(count, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the array int array response.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> GetSimpleArrayIntArrayResponseAsync(this IDeepSleepApi operations, int? count = default(int?), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSimpleArrayIntArrayResponseWithHttpMessagesAsync(count, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            public static void HeadSimpleArrayIntArrayResponse(this IDeepSleepApi operations, int? count = default(int?))
            {
                operations.HeadSimpleArrayIntArrayResponseAsync(count).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='count'>
            /// The count.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadSimpleArrayIntArrayResponseAsync(this IDeepSleepApi operations, int? count = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadSimpleArrayIntArrayResponseWithHttpMessagesAsync(count, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Simples the array int array request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The ints.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static IList<int?> PostSimpleArrayIntArrayRequest(this IDeepSleepApi operations, IList<int?> body = default(IList<int?>), string xCorrelationId = default(string))
            {
                return operations.PostSimpleArrayIntArrayRequestAsync(body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the array int array request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The ints.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<int?>> PostSimpleArrayIntArrayRequestAsync(this IDeepSleepApi operations, IList<int?> body = default(IList<int?>), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostSimpleArrayIntArrayRequestWithHttpMessagesAsync(body, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Simples the i list int array query string.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static int? GetSimpleIlistIntArrayQuerystring(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), string xCorrelationId = default(string))
            {
                return operations.GetSimpleIlistIntArrayQuerystringAsync(queryItems, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the i list int array query string.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<int?> GetSimpleIlistIntArrayQuerystringAsync(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSimpleIlistIntArrayQuerystringWithHttpMessagesAsync(queryItems, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            public static void HeadSimpleIlistIntArrayQuerystring(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>))
            {
                operations.HeadSimpleIlistIntArrayQuerystringAsync(queryItems).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadSimpleIlistIntArrayQuerystringAsync(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadSimpleIlistIntArrayQuerystringWithHttpMessagesAsync(queryItems, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Simples the i enumerable int array query string.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static int? GetSimpleIenumerableIntArrayQuerystring(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), string xCorrelationId = default(string))
            {
                return operations.GetSimpleIenumerableIntArrayQuerystringAsync(queryItems, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the i enumerable int array query string.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<int?> GetSimpleIenumerableIntArrayQuerystringAsync(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSimpleIenumerableIntArrayQuerystringWithHttpMessagesAsync(queryItems, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            public static void HeadSimpleIenumerableIntArrayQuerystring(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>))
            {
                operations.HeadSimpleIenumerableIntArrayQuerystringAsync(queryItems).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadSimpleIenumerableIntArrayQuerystringAsync(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadSimpleIenumerableIntArrayQuerystringWithHttpMessagesAsync(queryItems, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Simples the array int array query string.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static int? GetSimpleArrayIntArrayQuerystring(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), string xCorrelationId = default(string))
            {
                return operations.GetSimpleArrayIntArrayQuerystringAsync(queryItems, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Simples the array int array query string.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<int?> GetSimpleArrayIntArrayQuerystringAsync(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetSimpleArrayIntArrayQuerystringWithHttpMessagesAsync(queryItems, xCorrelationId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            public static void HeadSimpleArrayIntArrayQuerystring(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>))
            {
                operations.HeadSimpleArrayIntArrayQuerystringAsync(queryItems).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='queryItems'>
            /// The query items.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HeadSimpleArrayIntArrayQuerystringAsync(this IDeepSleepApi operations, IList<int?> queryItems = default(IList<int?>), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.HeadSimpleArrayIntArrayQuerystringWithHttpMessagesAsync(queryItems, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Posts the basic object model with void return.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model with void return.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static void PostBasicObjectModelReturnVoid(this IDeepSleepApi operations, BasicObject body = default(BasicObject), string xCorrelationId = default(string))
            {
                operations.PostBasicObjectModelReturnVoidAsync(body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Posts the basic object model with void return.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model with void return.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostBasicObjectModelReturnVoidAsync(this IDeepSleepApi operations, BasicObject body = default(BasicObject), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostBasicObjectModelReturnVoidWithHttpMessagesAsync(body, xCorrelationId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Posts the basic object model with task return.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model with task return.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static void PostBasicObjectModelReturnTask(this IDeepSleepApi operations, BasicObject body = default(BasicObject), string xCorrelationId = default(string))
            {
                operations.PostBasicObjectModelReturnTaskAsync(body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Posts the basic object model with task return.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model with task return.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostBasicObjectModelReturnTaskAsync(this IDeepSleepApi operations, BasicObject body = default(BasicObject), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostBasicObjectModelReturnTaskWithHttpMessagesAsync(body, xCorrelationId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Posts the basic object model with task 202 return.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model with task 202 return.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            public static void PostBasicObjectModelReturnTaskWith202Attribute(this IDeepSleepApi operations, BasicObject body = default(BasicObject), string xCorrelationId = default(string))
            {
                operations.PostBasicObjectModelReturnTaskWith202AttributeAsync(body, xCorrelationId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Posts the basic object model with task 202 return.
            /// </summary>
            /// <remarks>
            /// Offically posts the basic object model with task 202 return.
            /// Here's some documentation:
            /// &lt;a href="http://www.google.com" /&gt;.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The request.
            /// </param>
            /// <param name='xCorrelationId'>
            /// A correlation value that will be echoed back within the X-CorrelationId
            /// response header.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostBasicObjectModelReturnTaskWith202AttributeAsync(this IDeepSleepApi operations, BasicObject body = default(BasicObject), string xCorrelationId = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.PostBasicObjectModelReturnTaskWith202AttributeWithHttpMessagesAsync(body, xCorrelationId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
