// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v2.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomObjectIdModel
    {
        /// <summary>
        /// Initializes a new instance of the CustomObjectIdModel class.
        /// </summary>
        public CustomObjectIdModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomObjectIdModel class.
        /// </summary>
        public CustomObjectIdModel(int? id = default(int?), string value = default(string), CustomObjectModel inherited = default(CustomObjectModel), IList<CustomObjectModel> innerModels = default(IList<CustomObjectModel>), IDictionary<string, CustomObjectModel> keyedModels = default(IDictionary<string, CustomObjectModel>), SecondCustomObject secondObject = default(SecondCustomObject))
        {
            Id = id;
            Value = value;
            Inherited = inherited;
            InnerModels = innerModels;
            KeyedModels = keyedModels;
            SecondObject = secondObject;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inherited")]
        public CustomObjectModel Inherited { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerModels")]
        public IList<CustomObjectModel> InnerModels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keyedModels")]
        public IDictionary<string, CustomObjectModel> KeyedModels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondObject")]
        public SecondCustomObject SecondObject { get; set; }

    }
}
