// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v2.Models
{

    /// <summary>
    /// Defines values for TestEnum.
    /// </summary>
    public static class TestEnum
    {
        /// <summary>
        /// Represents the default value of the enum
        /// </summary>
        public const string None = "None";
        /// <summary>
        /// The item 1 member
        /// </summary>
        public const string Item1 = "Item1";
        /// <summary>
        /// The item 2 member
        /// </summary>
        public const string Item2 = "Item2";
    }
}
