// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v3.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ThirdCustomObject
    {
        /// <summary>
        /// Initializes a new instance of the ThirdCustomObject class.
        /// </summary>
        public ThirdCustomObject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ThirdCustomObject class.
        /// </summary>
        public ThirdCustomObject(CustomObjectModel inherited = default(CustomObjectModel), IList<CustomObjectModel> innerModels = default(IList<CustomObjectModel>), IDictionary<string, CustomObjectModel> keyedModels = default(IDictionary<string, CustomObjectModel>), IDictionary<string, ThirdCustomObject> keyedThirdModels = default(IDictionary<string, ThirdCustomObject>), IDictionary<string, SecondCustomObject> keyedSecondModels = default(IDictionary<string, SecondCustomObject>), SecondCustomObject secondObject = default(SecondCustomObject), ThirdCustomObject thirdObject = default(ThirdCustomObject), CustomObjectIdModel idModel = default(CustomObjectIdModel), CustomObjectModel model = default(CustomObjectModel))
        {
            Inherited = inherited;
            InnerModels = innerModels;
            KeyedModels = keyedModels;
            KeyedThirdModels = keyedThirdModels;
            KeyedSecondModels = keyedSecondModels;
            SecondObject = secondObject;
            ThirdObject = thirdObject;
            IdModel = idModel;
            Model = model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inherited")]
        public CustomObjectModel Inherited { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerModels")]
        public IList<CustomObjectModel> InnerModels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keyedModels")]
        public IDictionary<string, CustomObjectModel> KeyedModels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keyedThirdModels")]
        public IDictionary<string, ThirdCustomObject> KeyedThirdModels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keyedSecondModels")]
        public IDictionary<string, SecondCustomObject> KeyedSecondModels { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondObject")]
        public SecondCustomObject SecondObject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thirdObject")]
        public ThirdCustomObject ThirdObject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idModel")]
        public CustomObjectIdModel IdModel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public CustomObjectModel Model { get; set; }

    }
}
