//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepSleep.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthenticationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeepSleep.Auth.AuthenticationErrors", typeof(AuthenticationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.06|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string EmptyAuthField {
            get {
                return ResourceManager.GetString("EmptyAuthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.01|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string EmptySignature {
            get {
                return ResourceManager.GetString("EmptySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.02|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string InvalidAPIKey {
            get {
                return ResourceManager.GetString("InvalidAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.07|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string InvalidAuthValuePairing {
            get {
                return ResourceManager.GetString("InvalidAuthValuePairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.09|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string InvalidPrivateKey {
            get {
                return ResourceManager.GetString("InvalidPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.08|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string InvalidPublicKey {
            get {
                return ResourceManager.GetString("InvalidPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.03|Error|Invalid Authentication|Query string signature placement is not supported for this authentication scheme..
        /// </summary>
        internal static string InvalidQueryStringPlacementForSignature {
            get {
                return ResourceManager.GetString("InvalidQueryStringPlacementForSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.04|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string InvalidSignature {
            get {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.05|Error|Invalid Authentication|Invalid authentication..
        /// </summary>
        internal static string UnknownAuthType {
            get {
                return ResourceManager.GetString("UnknownAuthType", resourceCulture);
            }
        }
    }
}
