// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v3.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The basic object
    /// </summary>
    public partial class BasicObject
    {
        /// <summary>
        /// Initializes a new instance of the BasicObject class.
        /// </summary>
        public BasicObject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BasicObject class.
        /// </summary>
        /// <param name="nullableInt32">Gets or sets the nullable
        /// int32.</param>
        /// <param name="int32">Gets or sets the int32.</param>
        /// <param name="guidObject">Gets or sets the unique identifier
        /// object.</param>
        /// <param name="nullableGuidObject">Gets or sets the nullable unique
        /// identifier object.</param>
        /// <param name="uriObject">Gets or sets the URI object.</param>
        /// <param name="stringObject">Gets or sets the string object.</param>
        /// <param name="enumObject">Possible values include: 'None',
        /// 'Something1', 'Something2'</param>
        /// <param name="nullableEnumObject">Possible values include: 'None',
        /// 'Something1', 'Something2'</param>
        /// <param name="floatObject">Gets or sets the float object.</param>
        /// <param name="decimalObject">Gets or sets the decimal
        /// object.</param>
        /// <param name="doubleObject">Gets or sets the double object.</param>
        /// <param name="shortObject">Gets or sets the short object.</param>
        /// <param name="byteObject">Gets or sets the byte object.</param>
        /// <param name="sByteObject">Gets or sets the s byte object.</param>
        /// <param name="timeSpanObject">Gets or sets the time span
        /// object.</param>
        /// <param name="boolObject">Gets or sets a value indicating whether
        /// [bool object].</param>
        /// <param name="nullableBoolObject">Gets or sets the nullable bool
        /// object.</param>
        /// <param name="dateTimeObject">Gets or sets the date time
        /// object.</param>
        /// <param name="nullableDateTimeObject">Gets or sets the nullable date
        /// time object.</param>
        /// <param name="dateTimeOffsetObject">Gets or sets the date time
        /// offset object.</param>
        /// <param name="nullableDateTimeOffsetObject">Gets or sets the
        /// nullable date time offset object.</param>
        /// <param name="longObject">Gets or sets the long object.</param>
        /// <param name="charObject">Gets or sets the character object.</param>
        public BasicObject(int? nullableInt32 = default(int?), int? int32 = default(int?), System.Guid? guidObject = default(System.Guid?), System.Guid? nullableGuidObject = default(System.Guid?), string uriObject = default(string), string stringObject = default(string), string enumObject = default(string), string nullableEnumObject = default(string), double? floatObject = default(double?), double? decimalObject = default(double?), double? doubleObject = default(double?), int? shortObject = default(int?), int? byteObject = default(int?), int? sByteObject = default(int?), string timeSpanObject = default(string), bool? boolObject = default(bool?), bool? nullableBoolObject = default(bool?), System.DateTimeOffset? dateTimeObject = default(System.DateTimeOffset?), System.DateTimeOffset? nullableDateTimeObject = default(System.DateTimeOffset?), System.DateTimeOffset? dateTimeOffsetObject = default(System.DateTimeOffset?), System.DateTimeOffset? nullableDateTimeOffsetObject = default(System.DateTimeOffset?), long? longObject = default(long?), string charObject = default(string))
        {
            NullableInt32 = nullableInt32;
            Int32 = int32;
            GuidObject = guidObject;
            NullableGuidObject = nullableGuidObject;
            UriObject = uriObject;
            StringObject = stringObject;
            EnumObject = enumObject;
            NullableEnumObject = nullableEnumObject;
            FloatObject = floatObject;
            DecimalObject = decimalObject;
            DoubleObject = doubleObject;
            ShortObject = shortObject;
            ByteObject = byteObject;
            SByteObject = sByteObject;
            TimeSpanObject = timeSpanObject;
            BoolObject = boolObject;
            NullableBoolObject = nullableBoolObject;
            DateTimeObject = dateTimeObject;
            NullableDateTimeObject = nullableDateTimeObject;
            DateTimeOffsetObject = dateTimeOffsetObject;
            NullableDateTimeOffsetObject = nullableDateTimeOffsetObject;
            LongObject = longObject;
            CharObject = charObject;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the nullable int32.
        /// </summary>
        [JsonProperty(PropertyName = "nullableInt32")]
        public int? NullableInt32 { get; set; }

        /// <summary>
        /// Gets or sets the int32.
        /// </summary>
        [JsonProperty(PropertyName = "int32")]
        public int? Int32 { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier object.
        /// </summary>
        [JsonProperty(PropertyName = "guidObject")]
        public System.Guid? GuidObject { get; set; }

        /// <summary>
        /// Gets or sets the nullable unique identifier object.
        /// </summary>
        [JsonProperty(PropertyName = "nullableGuidObject")]
        public System.Guid? NullableGuidObject { get; set; }

        /// <summary>
        /// Gets or sets the URI object.
        /// </summary>
        [JsonProperty(PropertyName = "uriObject")]
        public string UriObject { get; set; }

        /// <summary>
        /// Gets or sets the string object.
        /// </summary>
        [JsonProperty(PropertyName = "stringObject")]
        public string StringObject { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'Something1',
        /// 'Something2'
        /// </summary>
        [JsonProperty(PropertyName = "enumObject")]
        public string EnumObject { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'None', 'Something1',
        /// 'Something2'
        /// </summary>
        [JsonProperty(PropertyName = "nullableEnumObject")]
        public string NullableEnumObject { get; set; }

        /// <summary>
        /// Gets or sets the float object.
        /// </summary>
        [JsonProperty(PropertyName = "floatObject")]
        public double? FloatObject { get; set; }

        /// <summary>
        /// Gets or sets the decimal object.
        /// </summary>
        [JsonProperty(PropertyName = "decimalObject")]
        public double? DecimalObject { get; set; }

        /// <summary>
        /// Gets or sets the double object.
        /// </summary>
        [JsonProperty(PropertyName = "doubleObject")]
        public double? DoubleObject { get; set; }

        /// <summary>
        /// Gets or sets the short object.
        /// </summary>
        [JsonProperty(PropertyName = "shortObject")]
        public int? ShortObject { get; set; }

        /// <summary>
        /// Gets or sets the byte object.
        /// </summary>
        [JsonProperty(PropertyName = "byteObject")]
        public int? ByteObject { get; set; }

        /// <summary>
        /// Gets or sets the s byte object.
        /// </summary>
        [JsonProperty(PropertyName = "sByteObject")]
        public int? SByteObject { get; set; }

        /// <summary>
        /// Gets or sets the time span object.
        /// </summary>
        [JsonProperty(PropertyName = "timeSpanObject")]
        public string TimeSpanObject { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [bool object].
        /// </summary>
        [JsonProperty(PropertyName = "boolObject")]
        public bool? BoolObject { get; set; }

        /// <summary>
        /// Gets or sets the nullable bool object.
        /// </summary>
        [JsonProperty(PropertyName = "nullableBoolObject")]
        public bool? NullableBoolObject { get; set; }

        /// <summary>
        /// Gets or sets the date time object.
        /// </summary>
        [JsonProperty(PropertyName = "dateTimeObject")]
        public System.DateTimeOffset? DateTimeObject { get; set; }

        /// <summary>
        /// Gets or sets the nullable date time object.
        /// </summary>
        [JsonProperty(PropertyName = "nullableDateTimeObject")]
        public System.DateTimeOffset? NullableDateTimeObject { get; set; }

        /// <summary>
        /// Gets or sets the date time offset object.
        /// </summary>
        [JsonProperty(PropertyName = "dateTimeOffsetObject")]
        public System.DateTimeOffset? DateTimeOffsetObject { get; set; }

        /// <summary>
        /// Gets or sets the nullable date time offset object.
        /// </summary>
        [JsonProperty(PropertyName = "nullableDateTimeOffsetObject")]
        public System.DateTimeOffset? NullableDateTimeOffsetObject { get; set; }

        /// <summary>
        /// Gets or sets the long object.
        /// </summary>
        [JsonProperty(PropertyName = "longObject")]
        public long? LongObject { get; set; }

        /// <summary>
        /// Gets or sets the character object.
        /// </summary>
        [JsonProperty(PropertyName = "charObject")]
        public string CharObject { get; set; }

    }
}
