// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DeepSleep.Api.OpenApiCheckTests.v3.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a uri object model used in requests that contains int32
    /// items
    /// </summary>
    public partial class Int32ObjectModelRq
    {
        /// <summary>
        /// Initializes a new instance of the Int32ObjectModelRq class.
        /// </summary>
        public Int32ObjectModelRq()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Int32ObjectModelRq class.
        /// </summary>
        /// <param name="int32Property">Gets or sets the int32
        /// property.</param>
        /// <param name="nullableInt32Property">Gets or sets the nullable int32
        /// property.</param>
        /// <param name="uInt32Property">Gets or sets the u int32
        /// property.</param>
        /// <param name="nullableUInt32Property">Gets or sets the nullable u
        /// int32 property.</param>
        public Int32ObjectModelRq(int? int32Property = default(int?), int? nullableInt32Property = default(int?), int? uInt32Property = default(int?), int? nullableUInt32Property = default(int?))
        {
            Int32Property = int32Property;
            NullableInt32Property = nullableInt32Property;
            UInt32Property = uInt32Property;
            NullableUInt32Property = nullableUInt32Property;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the int32 property.
        /// </summary>
        [JsonProperty(PropertyName = "int32Property")]
        public int? Int32Property { get; set; }

        /// <summary>
        /// Gets or sets the nullable int32 property.
        /// </summary>
        [JsonProperty(PropertyName = "nullableInt32Property")]
        public int? NullableInt32Property { get; set; }

        /// <summary>
        /// Gets or sets the u int32 property.
        /// </summary>
        [JsonProperty(PropertyName = "uInt32Property")]
        public int? UInt32Property { get; set; }

        /// <summary>
        /// Gets or sets the nullable u int32 property.
        /// </summary>
        [JsonProperty(PropertyName = "nullableUInt32Property")]
        public int? NullableUInt32Property { get; set; }

    }
}
