name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .Net 3.1.x'
  inputs:
    version: 3.1.x

- task: UseDotNet@2
  displayName: 'Use .Net 5.0.x'
  inputs:
    version: 5.0.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet resotre'
  inputs:
    command: restore
    projects: '**/*.sln'
    feedsToUse: config
    nugetConfigPath: .nuget/NuGet.Config

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: DeepSleep.sln
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" --no-build'
    publishTestResults: false

- task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
  displayName: 'Generate Code Coverage Report'
  inputs:
    reports: '$(Build.SourcesDirectory)/**/*.cobertura.xml'
    targetdir: '$(Build.SourcesDirectory)/CodeCoverage'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
    classfilters: '+*;-DeepSleep.Api.*;-Api.DeepSleep.*'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact:'
  inputs:
    ArtifactName: DeepSleep

